openapi: 3.0.0
info:
  title: Employee API
  version: 1.0.0
  description: A simple API for managing employees
servers:
  - url: http://localhost:8080  # For testing purposes

components:
  schemas:
    Employee:
      type: object
      properties:
        id:
          type: integer
          format: int64
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        hire_date:
          type: string
          format: date
      
    New_Employee:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string
        hire_date:
          type: string
          format: date
          
    Update_Employee:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        email:
          type: string


    Error:
      type: object
      properties:
        code:
          type: integer
          description: The error code.
        message:
          type: string
          description: A human-readable description of the error.
          
paths:
  /employees:
    get:
      summary: Retrieve a list of employees
      description: Lists all employees in the employees table.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Employee'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/Error' 
    post:
      summary: Creates a new employee record in the database
      description: Creates a new employee record in the database by adding a new row.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/New_Employee'
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Data successfully inserted.
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
                
  /employees/{id}:
    get:
      summary: Retrieve an employee by ID
      description: Retrieves an employee record by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            description: The value of the ID column in the employee table used for looking up the employee
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Employee'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error' 
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    put:
      summary: Update an employee by ID
      description: Updates an employee record by their ID.
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
            description: The value of the ID column in the employee table used for looking up the employee
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Update_Employee'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 'Successfully updated data for ID : 5'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
    
    delete: 
      summary: Delete an employee by ID
      description: Deletes an employee record by their ID.
      parameters:
        - in: path  
          name: id 
          required: true  
          schema:
            type: integer
            format: int64
            description: The unique identifier of the employee to be deleted.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 'Successfully deleted data for ID : 5'
        '400':  
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                
                

